filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message

processors:
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "api-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"

setup.template.enabled: true
setup.ilm.enabled: false
